spring:
  datasource:
    url: jdbc:mysql//localhost:3306/homestay?useSSL=false&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 192.168.180.100
      port: 6379
      password: 3355717135
server:
  port: 6666
